name: xata_dart
description: XATA SDK for dart
version: 0.0.1
repository: https://github.com/alselawi/xata

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
